services:
  payloadr:
    build: .
    container_name: payloadr

    ports:
      - "5050:5000"

    environment:
      PAYLOADR_PATHS: /downloads,/movies,/shows,/anime,/music,/anime-shows

    volumes:
      - /srv/downloads:/downloads
      - /srv/media/movies:/movies
      - /srv/media/shows:/shows
      - /srv/media/anime:/anime
      - /srv/media/music:/music
      - /srv/media/anime-shows:/anime-shows

    restart: unless-stopped